# Generated by Django 4.0.4 on 2022-05-10 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tests', '0004_usertestrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='readers',
            field=models.ManyToManyField(related_name='tests', through='tests.UserTestRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
