# Generated by Django 4.0.4 on 2022-05-11 10:25

from django.db import migrations, models
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_usertestrelation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=100, validators=[tests.models.test_val], verbose_name='Название теста'),
        ),
    ]
