# Generated by Django 4.0.4 on 2022-05-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
    ]
