# Generated by Django 4.0.5 on 2022-07-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_delete_historicalcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalanswer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ответ', 'verbose_name_plural': 'historical Ответы'},
        ),
        migrations.AlterModelOptions(
            name='historicalquestion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Вопрос', 'verbose_name_plural': 'historical Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='historicaltest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Тест', 'verbose_name_plural': 'historical Тесты'},
        ),
        migrations.AlterModelOptions(
            name='historicalusertestrelation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user test relation', 'verbose_name_plural': 'historical user test relations'},
        ),
        migrations.RemoveField(
            model_name='historicaltest',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='test',
            name='owner',
        ),
        migrations.AlterField(
            model_name='historicalanswer',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltest',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalusertestrelation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
